name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v3
        with:
          version: 9.7.0
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.12.2
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - name: Lint
        run: pnpm lint
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v3
        with:
          version: 9.7.0
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.12.2
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - name: Print working directory
        run: pwd
      - name: List directory contents before build
        run: ls -la
      - name: Build
        run: pnpm build
      - name: List directory contents after build
        run: ls -la
      - name: Check for .next directory
        run: |
          if [ -d ".next" ]; then
            echo ".next directory exists"
            ls -la .next
          else
            echo ".next directory does not exist"
            echo "Contents of current directory:"
            ls -la
          fi
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: next
          path: .next
          if-no-files-found: error
      - name: List .next directory contents
        if: failure()
        run: |
          echo "Listing contents of the current directory:"
          ls -la
          echo "Attempting to list contents of .next directory:"
          ls -la .next || echo ".next directory not found"
  test:
    needs: [build, lint]
    timeout-minutes: 60
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v3
        with:
          version: 9.7.0
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.12.2
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - uses: actions/download-artifact@v4
        with:
          name: next
          path: .next
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Start server and run tests
        run: pnpm exec playwright test
