name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v3
        with:
          version: 9.7.0
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.12.2
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - name: Lint
        run: pnpm lint

  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v3
        with:
          version: 9.7.0
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.12.2
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - name: Build
        run: pnpm build
      - name: List dist directory
        run: |
          echo "Contents of dist directory:"
          ls -la dist
          echo "Total size of dist directory:"
          du -sh dist
      - name: Upload dist directory
        uses: actions/upload-artifact@v4
        with:
          name: dist-artifact
          path: ${{ github.workspace }}/dist
          if-no-files-found: error

  install-browsers:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 9.7.0
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.12.2
          cache: "pnpm"
      - name: Install Playwright
        run: pnpm add -D @playwright/test
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Cache Playwright browsers
        uses: actions/cache@v3
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-playwright-

  test:
    needs: [build, install-browsers]
    timeout-minutes: 60
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v3
        with:
          version: 9.7.0
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.12.2
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - name: Restore Playwright browsers
        uses: actions/cache@v3
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('**/pnpm-lock.yaml') }}
      - uses: actions/download-artifact@v4
        with:
          name: dist-artifact
          path: dist
      - name: List downloaded dist directory
        run: |
          echo "Contents of downloaded dist directory:"
          ls -la dist
      - name: Run Playwright tests
        run: pnpm exec playwright test
